version: '3.8'

services:
  postgres-prisma-wanago:
    image: postgres:latest
    container_name: postgres-prisma-wanago
    restart: on-failure
    healthcheck:
      test: 'exit 0'
    ports:
      - '5433:5432'
    environment:
      - POSTGRES_DB=${POSTGRES_DATABASE}
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_MULTIPLE_EXTENSIONS=postgis,hstore,postgis_topology,postgis_raster,pgrouting
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
    driver: local
