version: "3"
services:
  postgres:
    container_name: nestjs-postgres
    image: postgres:latest
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/data/postgres
    env_file:
      - docker.env
    networks:
      - postgres

  pgadmin:
    links:
      - postgres:postgres
    container_name: nestjs-pgadmin
    image: dpage/pgadmin4
    ports:
      - "8080:80"
    volumes:
      - pgadmin-data:/root/.pgadmin
    env_file:
      - docker.env
    networks:
      - postgres

volumes:
  postgres-data:
  pgadmin-data:


networks:
  postgres:
    driver: bridge
