version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: nestjs-postgres
    restart: on-failure
    healthcheck:
      test: 'exit 0'
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/data/postgres
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST_AUTH_METHOD=trust

volumes:
  postgres-data:
